name: ShopperMatters
favicon: null
layout_spectrum: 0.92991
typography_spectrum: 0.32990677119232714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cc0000'
    - '#000000'
    - '#ffcc00'
    - '#6e6e6e'
  brandStrength: 0.26717016007751226
  lightness: 0.09623510111123323
  saturation: 0.9547893565613776
  rhythmicContrast: 0.8578522212337703
purpose: []
